"""books-chage

Revision ID: 507b66c96f22
Revises: bbea60add636
Create Date: 2021-09-17 09:43:02.087201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507b66c96f22'
down_revision = 'bbea60add636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'book_id')
    # ### end Alembic commands ###
