"""books-modified

Revision ID: a02f1c4fe92e
Revises: 507b66c96f22
Create Date: 2021-09-17 10:54:51.512364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02f1c4fe92e'
down_revision = '507b66c96f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_title', sa.String(), nullable=True))
    op.add_column('books', sa.Column('book_thumb', sa.String(), nullable=True))
    op.add_column('books', sa.Column('book_author', sa.String(), nullable=True))
    op.add_column('books', sa.Column('book_page', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('book_rating', sa.String(), nullable=True))
    op.drop_column('books', 'book_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_info', sa.VARCHAR(), nullable=True))
    op.drop_column('books', 'book_rating')
    op.drop_column('books', 'book_page')
    op.drop_column('books', 'book_author')
    op.drop_column('books', 'book_thumb')
    op.drop_column('books', 'book_title')
    # ### end Alembic commands ###
